---
services:
  backend:
    image: 4gray/iptvnator-backend:latest
    ports:
      - "7333:3000"
    environment:
      - CLIENT_URL=http://localhost:4334
      # this one should match with the address and port in frontend CLIENT_URL env
      
  frontend:
    image: iptvnator-fixed:latest
    ports:
      - "4334:80"
    environment:
      - BACKEND_URL=http://localhost:7333 
      # this one should match with the address of the backend service
      
